### ISSUE TITLE
feat: add global config

### ISSUE THREAD

**Issue by ximenesyuri** [ximenesyuri/comma#7]
# Description

It would be interesting to have global settings, as:

1. `editor`: to be used while opening the temporary file to collect an input and with `g proj .`
2. `browser`: to be used with `g proj_name . something`
3. `labels`: to be used with `g proj_name u/update l/labels`
4. ...

The configurations should be set in envs:
1. `G_EDITOR`
2. `G_BROWSER`
3. `G_LABELS=(label1 label2 ...)`

Or in the configuration file `g.yml`:

```yaml
globals:
    editor:
    browser:
    labels:
        - label 1
        - label 2
    ...
```
